### ISSUE TITLE
Just a Black Screen (But Can Hear Sound)

### ISSUE THREAD

**Issue by casbboy** [yanwsh/videojs-panorama#123]
I see the Panorama icon appearing in the tool bar, but no video is showing.

I'm testing it here:

https://www.traileraddict.com/the-conjuring-2/360-vr-experience-enfield

Seeing lots of errors from the three.js as well.

Anything I'm missing?

Cheers!
Ryan

**Comment by casbboy** [comment]
I guess it's because my video is monoscopic? Does this plugin support that?

**Comment by yanwsh** [comment]
i can play the video because it shows video.js is undefined, please make sure you include video.js script. and let me know when it's done, i can test again.

**Comment by casbboy** [comment]
@yanwsh 

I'm not having that issue in my console. But here is the errors that start once I hit play:

Here are the scripts being loaded:


<script src="/videojs/videojs-ie8.min.js"></script>
  | <link href="/videojs/video-js-3.min.css" rel="stylesheet">
  | <script src="//vjs.zencdn.net/5.19/video.min.js"></script>
  | 
  | <script src="/videojs/neuvo3.min.js"></script>
  | <script src="/videojs/videojs.theaterMode.js"></script>
  | <script src="https://cdnjs.cloudflare.com/ajax/libs/three.js/r76/three.js"></script>
  | <script src="/videojs/videojs-panorama.v5.min.js"></script>
  | <link href="/videojs/videojs-panorama.css" rel="stylesheet">



```
360-vr-experience-enfield:1 [.Offscreen-For-WebGL-0000019D1795F8E0]RENDER WARNING: there is no texture bound to the unit 0
360-vr-experience-enfield:1 [.Offscreen-For-WebGL-0000019D1795F8E0]RENDER WARNING: texture bound to texture unit 0 is not renderable. It maybe non-power-of-2 and have incompatible texture filtering.
three.js:31187 DOMException: Failed to execute 'texImage2D' on 'WebGLRenderingContext': The video element contains cross-origin data, and may not be loaded.
    at THREE.WebGLState.texImage2D (https://cdnjs.cloudflare.com/ajax/libs/three.js/r76/three.js:31183:18)
    at uploadTexture (https://cdnjs.cloudflare.com/ajax/libs/three.js/r76/three.js:27573:11)
    at THREE.WebGLRenderer.setTexture2D (https://cdnjs.cloudflare.com/ajax/libs/three.js/r76/three.js:27611:4)
    at SingleUniform.setValueT1 [as setValue] (https://cdnjs.cloudflare.com/ajax/libs/three.js/r76/three.js:31490:22)
    at Function.THREE.WebGLUniforms.WebGLUniforms.upload (https://cdnjs.cloudflare.com/ajax/libs/three.js/r76/three.js:31820:7)
    at setProgram (https://cdnjs.cloudflare.com/ajax/libs/three.js/r76/three.js:26727:24)
    at THREE.WebGLRenderer.renderBufferDirect (https://cdnjs.cloudflare.com/ajax/libs/three.js/r76/three.js:25522:17)
    at renderObjects (https://cdnjs.cloudflare.com/ajax/libs/three.js/r76/three.js:26289:11)
    at THREE.WebGLRenderer.render (https://cdnjs.cloudflare.com/ajax/libs/three.js/r76/three.js:26042:4)
    at constructor.render (https://www.traileraddict.com/videojs/videojs-panorama.v5.min.js:1:14609)
```

I tested the page in both browsers, I'm not getting that video.js error.

![panscreen](https://user-images.githubusercontent.com/17091513/28656699-45ea71b4-7258-11e7-98ac-fdcec102e950.jpg)

Cheers!
Ryan

**Comment by casbboy** [comment]
Just to be safe, I have:

player.panorama({
					clickAndDrag: true
				});

Run only after player.ready, ensures video js is up and running.

Cheers!
Ryan

**Comment by casbboy** [comment]
@yanwsh - was seeing if had a chance to check on this.

**Comment by yanwsh** [comment]
sorry for the late reply, I only have time during the weekend.

According to the demo you provide, it contains cross domain video, which is not supported by current browser,  you have three options to solve this problem,

1. add cross domain header to  video source, which could support on desktop browser, chrome, firefox and safari don't have problem, but it doesn't support ios safari, you will still get black screen.
2. use iframe and make sure iframe and video on the same domain, you can bypass cross domain issue. i have a example, please click [here](https://github.com/yanwsh/videojs-panorama/blob/master/iframe.html) and [here](https://github.com/yanwsh/videojs-panorama/blob/master/iframe-video.html) to view.
3. use reverse proxy, make sure video and page on the same domain.

**Comment by casbboy** [comment]
The video can never be the same domain, as it comes from a CDN/Platform service.

The cross domain is only an issue with this plugin, but not VideoJS in general I'm guessing? The video works perfect without the plugin, just looks odd (monoscopic). lol.

Cheers!
Ryan

**Comment by yanwsh** [comment]
I know, but browser rule only allow same domain video because of security reason. The easiest solution is options one which is possible to add a cross origin header at CDN platform. But it's not support ios safari. 

My suggestion is do option three, which use reverse proxy, it supports live stream. 

Please video and do 360 video is different story, 360 video need to get original video and process image at runtime, that's why it needs cross domain support.

**Comment by casbboy** [comment]
Damn. Okay. Was doing the 360 no issue with JWPlayer so was trying to see if still could work with VideoJS.

Wouldn't reverse proxy be a bandwidth issue? When doing 100TB in bandwidth I'm thinking that would just double it, right?

**Comment by yanwsh** [comment]
if you check jwplayer's demo, you can see they use cross domain for desktop and same domain for mobile.

<img width="631" alt="screen shot 2017-07-29 at 5 03 15 pm" src="https://user-images.githubusercontent.com/6547291/28748220-ef81dfe0-747f-11e7-9d81-17f64c754238.png">

<img width="899" alt="screen shot 2017-07-29 at 5 02 32 pm" src="https://user-images.githubusercontent.com/6547291/28748221-f96cb430-747f-11e7-907a-5480b0ca149e.png">

And the cross domain header contain access-control-allow-origin header. 

If you are worry about bandwidth, maybe use can do the same thing.

**Comment by yanwsh** [comment]
may be you can use iframe solution, which add a html page on cdn. So it will solve cross domain issue.

**Comment by casbboy** [comment]
Well, I was pulling videos from another CDN, and just using the player (JWPlayer).

I'm piggybacking the Vimeo CDN. Was using JWPlayer just for the player, and the 360 video would appear there. 

So JWPlayer embedded on my domain, with video coming from elsewhere. So three domains at play.

**Comment by dinhtienvu** [comment]
@casbboy 
Can you tell me how to use Vimeo CDN and play it on iPhone iOS.
I still black sreen on iOS
