### ISSUE TITLE
Not working on Chrome 35

### ISSUE THREAD

**Issue by ChoOo7** [yanwsh/videojs-panorama#62]
Hello

It's now working on chrome 35

StackTrace : 
"TypeError: Failed to execute 'texImage2D' on 'WebGLRenderingContext': No function was found that matched the signature provided.
    at TypeError (native)
    at texImage2D (https://XXX/test/js/XX-videojs.360.min.js:31190:18)
    at uploadTexture (https://XXX/test/js/XX-videojs.360.min.js:27580:11)
    at setTexture2D (https://XXX/test/js/XX-videojs.360.min.js:27618:4)
    at SingleUniform.THREE.WebGLUniforms.setValueT1 [as setValue] (https://XXX/test/js/XX-videojs.360.min.js:31497:22)
    at Function.THREE.WebGLUniforms.WebGLUniforms.upload (https://XXX/test/js/XX-videojs.360.min.js:31827:7)
    at setProgram (https://XXX/test/js/XX-videojs.360.min.js:26734:24)
    at renderBufferDirect (https://XXX/test/js/XX-videojs.360.min.js:25529:17)
    at renderObjects (https://XXX/test/js/XX-videojs.360.min.js:26296:11)
    at render (https://XXX/test/js/XX-videojs.360.min.js:26049:4)"

Any chance to have it working one day ?

Thanks

**Comment by yanwsh** [comment]
Hello, did you add three.js plugin? I tested on chrome 35, and don't find this issue. Could you provide me a demo if you can? yanwsh@gmail.com, Thanks.
